name: Scheduled Terraform Drift Detection

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '*/30 * * * *'

jobs:
  drift-detection:
    name: Check Drift

    permissions:
      id-token: write
      contents: read
      pull-requests: read
      checks: read

    runs-on: ubuntu-latest

    steps:
      ### Check out the code

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      ### Install tooling

      - name: Install Terramate
        uses: terramate-io/terramate-action@v1

      - name: Install asdf
        uses: asdf-vm/actions/setup@v3

      - name: Install Terraform with asdf
        run: |
          asdf plugin add terraform
          asdf install terraform

      ### Check for drifted stacks

      - name: List changed stacks
        id: list-drifted
        run: terramate list -C stacks --cloud-status=drifted

      ### Configure cloud credentials

      - name: Configure AWS credentials
        if: steps.list-drifted.outputs.stdout
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github
        env:
          AWS_REGION: us-east-1
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}

      - name: Verify AWS credentials
        if: steps.list-drifted.outputs.stdout
        run: aws sts get-caller-identity

      ### Run Dift Check

      - name: Run Terraform init on all stacks
        if: steps.list-drifted.outputs.stdout
        run: |
          terramate script run \
            -C stacks \
            --parallel 1 \
            terraform init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run drift detection
        if: steps.list-drifted.outputs.stdout
        id: drift-detect
        run: |
          terramate script run \
            -C stacks \
            --parallel 5 \
            --continue-on-error \
            -- \
            terraform drift detect
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run drift reconciliation
        if: steps.list-drifted.outputs.stdout
        id: drift-reconcile
        run: |
          terramate script run \
            -C stacks \
            --tags reconcile \
            --parallel 5 \
            --continue-on-error \
            -- \
            terraform drift reconcile
        env:
          GITHUB_TOKEN: ${{ github.token }}
